modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="seasonals"
version="${file.jarVersion}"
displayName="Seasonals"
logoFile="seasonals.png"
credits="Thanks to Team Abnormals for creating Neapolitan."
authors="Uraneptus, EltrutLikes, cosmicgelatin"
description='''Addon for Neapolitan that adds seasonal flavors, including pumpkin and sweet berry.'''

[[dependencies.seasonals]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="neapolitan"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="blueprint"
    mandatory=true
    versionRange="[5.4.3,)"
    ordering="AFTER"
    side="BOTH"