modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="seasonals"
version="${file.jarVersion}"
displayName="Seasonals"
logoFile="seasonals.png"
credits="Thanks to Team Abnormals for creating Neapolitan."
authors="Uraneptus, EltrutLikes, cosmicgelatin"
description='''Addon for Neapolitan that adds seasonal flavors, including pumpkin and sweet berry.'''

[[dependencies.seasonals]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="neapolitan"
    mandatory=true
    versionRange="[2.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.1.1,)"
    ordering="AFTER"
    side="BOTH"