modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="seasonals"
version="${file.jarVersion}"
displayName="Seasonals"
logoFile="seasonals.png"
credits="Thanks to Team Abnormals for creating Neapolitan."
authors="Uraneptus, EltrutLikes, cosmicgelatin"
description='''Addon for Neapolitan that adds seasonal flavors, including pumpkin, beetroot and sweet berry.'''

[[dependencies.seasonals]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.seasonals]]
    modId="neapolitan"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.seasonals]]
    modId="blueprint"
    mandatory=true
    versionRange="[7.1.0,)"
    ordering="AFTER"
    side="BOTH"